In [2]:
import pandas as pd

In [3]:
data = pd.read_parquet('option_candles.parquet')
data.head(5)

,symbol,underlying,session_date,expiry,strike,option_type,epoch,ts,open,high,low,close,volume,open_interest
0,NSE:NIFTY2631024700CE,NSE:NIFTY50-INDEX,2026-03-04,2026-03-10,24700.0,CE,1772595900,2026-03-04 03:45:00,179.85,179.85,126.70,149.95,122720,771030
1,NSE:NIFTY2631024700CE,NSE:NIFTY50-INDEX,2026-03-04,2026-03-10,24700.0,CE,1772595905,2026-03-04 03:45:05,151.35,159.00,140.05,140.10,87100,771030
2,NSE:NIFTY2631024700CE,NSE:NIFTY50-INDEX,2026-03-04,2026-03-10,24700.0,CE,1772595910,2026-03-04 03:45:10,139.45,139.45,125.95,131.45,111085,771030
3,NSE:NIFTY2631024700CE,NSE:NIFTY50-INDEX,2026-03-04,2026-03-10,24700.0,CE,1772595915,2026-03-04 03:45:15,134.75,139.80,133.20,139.80,90090,771030
4,NSE:NIFTY2631024700CE,NSE:NIFTY50-INDEX,2026-03-04,2026-03-10,24700.0,CE,1772595920,2026-03-04 03:45:20,140.20,140.20,135.05,135.40,72280,771030

In [4]:
data['underlying'].value_counts()

underlying
NSE:NIFTYBANK-INDEX    1474270
NSE:NIFTY50-INDEX      1196978
Name: count, dtype: int64

In [5]:
data = pd.read_parquet('spot_candles.parquet')
data.head(5)

,symbol,session_date,epoch,ts,open,high,low,close,volume
0,NSE:INDIAVIX-INDEX,2025-12-01,1764560700,2025-12-01 03:45:00,11.62,11.62,10.90,11.23,0
1,NSE:INDIAVIX-INDEX,2025-12-01,1764560705,2025-12-01 03:45:05,11.24,11.49,10.92,11.19,0
2,NSE:INDIAVIX-INDEX,2025-12-01,1764560710,2025-12-01 03:45:10,11.28,11.28,11.23,11.26,0
3,NSE:INDIAVIX-INDEX,2025-12-01,1764560715,2025-12-01 03:45:15,11.25,11.30,11.24,11.30,0
4,NSE:INDIAVIX-INDEX,2025-12-01,1764560720,2025-12-01 03:45:20,11.31,11.31,11.30,11.30,0

In [11]:
data[data['symbol'] == 'NSE:NIFTYBANK-INDEX'].head(2)

,symbol,session_date,epoch,ts,open,high,low,close,volume
54000,NSE:NIFTYBANK-INDEX,2026-03-04,1772595900,2026-03-04 03:45:00,58447.15,58574.3,58393.55,58574.30,2177493
54001,NSE:NIFTYBANK-INDEX,2026-03-04,1772595905,2026-03-04 03:45:05,58586.00,58907.5,58586.00,58875.95,1408604

In [6]:
data['symbol'].value_counts()

symbol
NSE:NIFTY50-INDEX      319500
NSE:INDIAVIX-INDEX     301500
NSE:NIFTYBANK-INDEX    301500
Name: count, dtype: int64

In [7]:
data['ts'].min() + pd.Timedelta(hours=5, minutes=30)

Timestamp('2026-03-04 09:15:00')